POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Tris",
  "password": "12345"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Biene",
  "password": "98765"
}
