sequenceDiagram
        participant browser
        participant server
        browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
        activate server
        server-->>browser:HTML Document
        deactivate server
        browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
        activate server
        server-->>browser:main.css
        deactivate server
        browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
        activate server
        server-->>browser:spa.js
        Note right of browser: Starting JS that fetches JSON from the Server
        deactivate server
        browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
        activate server
        server-->>browser:[{ "content": "bonjouer", "date": "2025-06-25T20:21:08.585Z"},…]
        deactivate server
        Note right of browser: Callback Function that renders the notes
